package main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kaapija
 * 
 */
//package net.codejava.swing;


import java.util.Random;

import javax.swing.JOptionPane;

public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        visibilityGroup = new javax.swing.ButtonGroup();
        lightGlareGroup = new javax.swing.ButtonGroup();
        windGroup = new javax.swing.ButtonGroup();
        rangeGroup = new javax.swing.ButtonGroup();
        firingGroup = new javax.swing.ButtonGroup();
        situanationalGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        shootingValue = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        vI = new javax.swing.JRadioButton();
        vII = new javax.swing.JRadioButton();
        vIII = new javax.swing.JRadioButton();
        vIV = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lI = new javax.swing.JRadioButton();
        lII = new javax.swing.JRadioButton();
        lIII = new javax.swing.JRadioButton();
        lIV = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        wIV = new javax.swing.JRadioButton();
        wI = new javax.swing.JRadioButton();
        wII = new javax.swing.JRadioButton();
        wIII = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rIV = new javax.swing.JRadioButton();
        rI = new javax.swing.JRadioButton();
        rII = new javax.swing.JRadioButton();
        rIII = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        sI = new javax.swing.JCheckBox();
        sII = new javax.swing.JCheckBox();
        sIII = new javax.swing.JCheckBox();
        sIV = new javax.swing.JCheckBox();
        sV = new javax.swing.JCheckBox();
        sVI = new javax.swing.JCheckBox();
        sVII = new javax.swing.JCheckBox();
        sX = new javax.swing.JCheckBox();
        sXI = new javax.swing.JRadioButton();
        sVIII = new javax.swing.JRadioButton();
        sIX = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        accuracyValue = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        fV = new javax.swing.JRadioButton();
        fI = new javax.swing.JRadioButton();
        fII = new javax.swing.JRadioButton();
        fIII = new javax.swing.JRadioButton();
        fIV = new javax.swing.JRadioButton();
        shoot = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        edit = new javax.swing.JMenu();
        about = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Shooting skill:");

        shootingValue.setToolTipText("Your characters shooting value");
        shootingValue.setName("shootingValue"); // NOI18N
        shootingValue.setValue(14);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Visibility"));
        jPanel1.setToolTipText("Choose correct visibility. Default is clear = 0.");

        visibilityGroup.add(vI);
        vI.setText("Light Rain/Fog/Smoke");

        visibilityGroup.add(vII);
        vII.setText("Moderate Rain/Fog/Smoke");

        visibilityGroup.add(vIII);
        vIII.setText("Heavy Rain/Fog/Smoke");

        visibilityGroup.add(vIV);
        vIV.setSelected(true);
        vIV.setText("Clear");
        vIV.setToolTipText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vI)
                    .addComponent(vII)
                    .addComponent(vIII)
                    .addComponent(vIV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(vIV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vII, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vIII))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Light/Glare"));
        jPanel2.setToolTipText("Choose correct lighting and glare. Default is Full Light/No Glare = 0.");

        lightGlareGroup.add(lI);
        lI.setText("Partial Light/Weak Glare");

        lightGlareGroup.add(lII);
        lII.setText("Dim Light/Moderate Glare");

        lightGlareGroup.add(lIII);
        lIII.setText("Total Darkness/Blinding Glare");

        lightGlareGroup.add(lIV);
        lIV.setSelected(true);
        lIV.setText("Full Light/No Glare");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lI)
            .addComponent(lII)
            .addComponent(lIII)
            .addComponent(lIV)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lIV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lII)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lIII))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Wind"));
        jPanel3.setToolTipText("Choose correct wind condition. Default is None or Light Breeze = 0.");

        windGroup.add(wIV);
        wIV.setSelected(true);
        wIV.setText("None or Light Breeze");

        windGroup.add(wI);
        wI.setText("Light Winds");

        windGroup.add(wII);
        wII.setText("Moderate Winds");

        windGroup.add(wIII);
        wIII.setText("Strong Winds");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wIV)
                    .addComponent(wI)
                    .addComponent(wII)
                    .addComponent(wIII))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(wIV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wII)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wIII))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Range"));
        jPanel4.setToolTipText("Choose correct range. Default is Short = 0.");

        rangeGroup.add(rIV);
        rIV.setSelected(true);
        rIV.setText("Short");

        rangeGroup.add(rI);
        rI.setText("Medium");

        rangeGroup.add(rII);
        rII.setText("Long");

        rangeGroup.add(rIII);
        rIII.setText("Extreme");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rI)
                    .addComponent(rII)
                    .addComponent(rIII)
                    .addComponent(rIV))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(rIV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rII)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rIII))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Situational"));

        sI.setText("Attacker firing from cover with imaging device");
        sI.setToolTipText("-3");

        sII.setText("Attacker firing from a moving vehicle");
        sII.setToolTipText("-2");

        sIII.setText("Attacker in melee combat");
        sIII.setToolTipText("-3");

        sIV.setText("Attacker using off-hand weapon");
        sIV.setToolTipText("-2");

        sV.setText("Blind fire");
        sV.setToolTipText("-6");

        sVI.setText("Called shot");
        sVI.setToolTipText("-4");

        sVII.setText("Previously aimed with Take Aim");
        sVII.setToolTipText("+1 to hit & accuracy");

        sX.setText("Attacker running");
        sX.setToolTipText("-2");

        situanationalGroup.add(sXI);
        sXI.setSelected(true);
        sXI.setText("Dumb Gun");
        sXI.setToolTipText("No bonuses");

        situanationalGroup.add(sVIII);
        sVIII.setText("Wireless Smartgun(gear)");
        sVIII.setToolTipText("+1 to shoot and +2 to accuracy");

        situanationalGroup.add(sIX);
        sIX.setText("Wireless Smartgun(implanted");
        sIX.setToolTipText("+2 to shoot and +2 to accuracy");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sI)
                    .addComponent(sIII)
                    .addComponent(sII))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sIV)
                    .addComponent(sVI)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(sV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sX)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sVII)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(sXI)
                        .addGap(10, 10, 10)
                        .addComponent(sIX))
                    .addComponent(sVIII))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sI)
                    .addComponent(sIV)
                    .addComponent(sVII))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sII)
                    .addComponent(sV)
                    .addComponent(sX)
                    .addComponent(sXI)
                    .addComponent(sIX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sIII)
                    .addComponent(sVI)
                    .addComponent(sVIII))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jLabel2.setText("Accuracy:");

        accuracyValue.setToolTipText("Your guns accuracy");
        accuracyValue.setValue(5);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Firing mode"));
        jPanel7.setToolTipText("Choose correct firing mode. Default is Single-Shot (SS) and Semi-Automatic (SA) = 0.");

        firingGroup.add(fV);
        fV.setSelected(true);
        fV.setText("Single-Shot (SS) / Semi-Automatic (SA)");

        firingGroup.add(fI);
        fI.setText("Semi-Automatic Burst (SB)");

        firingGroup.add(fII);
        fII.setText("Burst Fire (BF)");

        firingGroup.add(fIII);
        fIII.setText("Long Burst (LB) or Full Auto (FA) (Simple)");

        firingGroup.add(fIV);
        fIV.setText("Full Auto (FA) (Complex)");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fV)
            .addComponent(fI)
            .addComponent(fII)
            .addComponent(fIII)
            .addComponent(fIV)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(fV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fII)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fIII)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fIV))
        );

        shoot.setText("Feuer frei!");
        shoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Compensate_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jButton1.setText("Roll 50k dice!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        file.setText("File");
        jMenuBar1.add(file);

        edit.setText("Edit");
        jMenuBar1.add(edit);

        about.setText("About");

        aboutMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        about.add(aboutMenu);

        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shootingValue)
                            .addComponent(jLabel2)
                            .addComponent(accuracyValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(shoot)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(shootingValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accuracyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shoot)
                            .addComponent(jButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        AboutForm form = new AboutForm();
        form.setVisible(true);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void shootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootActionPerformed
        int shootingSkill = (Integer) shootingValue.getValue();
        int diceToRoll;
        int gunAccuracy = (Integer) accuracyValue.getValue();
        if (sVII.isSelected()== true){
            gunAccuracy ++;
        }
        if (sVIII.isSelected()== true || sIX.isSelected() == true){
            gunAccuracy += 2;
        }
        int visibilityMod;
        int lightMod;
        int windMod;
        int rangeMod;
        int situationalMod;
        int hit = 0;
        int dodge;
        int glitch = 0;
        int rounds;
        visibilityMod = visibility();
        lightMod = lightning();
        windMod = wind();
        rangeMod = range();
        situationalMod = situational();
        diceToRoll = shootingSkill - visibilityMod - lightMod - windMod - rangeMod - situationalMod;
        dodge = dodgeThis();
        rounds = shotsFired();
        if(diceToRoll <= 0){
            infoBox("Ei noppia heitettäväksi!", "Epäonnistui");
        } else{
            Random rand = new Random();
            for(int i = 0; i < diceToRoll; i++){
            int  n = rand.nextInt(6) + 1;
            if(n >= 5){
               hit++;
            } else if( n == 1){
                glitch++;
            }
            }
            if(hit > gunAccuracy){
                hit = gunAccuracy;
            } if(glitch >= diceToRoll*0.5 && hit == 0){
                infoBox("Critical glitch!", "Epäonnistui!");
            }else if(glitch >= diceToRoll*0.5){  
                infoBox("Heitit "+diceToRoll+ " noppaa"+"\nSait "+hit+" osumaa" + "\nAmmuit " + rounds + " luotia" + "\nViholliselle tulee -" + dodge + " noppaa reactioon" , "Onnistui, mutta glitchasi!!");
            }
            else{
        infoBox("Heitit "+diceToRoll+ " noppaa"+"\nSait "+hit+" osumaa" + "\nAmmuit " + rounds + " luotia" + "\nViholliselle tulee -" + dodge + " noppaa reactioon" , "Onnistui!");
        }}
    }//GEN-LAST:event_shootActionPerformed
    private int shotsFired(){
        int modifier = 1;
        if (fI.isSelected()== true){
            modifier = 3;
        }
        if (fII.isSelected()== true){
            modifier = 3;
        }
        if (fIII.isSelected()== true){
            modifier = 5;
        }
        if (fIV.isSelected()== true){
            modifier = 9;
        }
        return modifier;
    }
    private int dodgeThis(){
        int modifier = 0;
        if (fI.isSelected()== true){
            modifier = 2;
        }
        if (fII.isSelected()== true){
            modifier = 2;
        }
        if (fIII.isSelected()== true){
            modifier = 5;
        }
        if (fIV.isSelected()== true){
            modifier = 9;
        }
        return modifier;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int yksi = 0;
       int kaksi = 0;
       int kolme = 0;
       int nelja = 0;
       int viisi = 0;
       int kuusi = 0;
       Random rand = new Random();
       for(int i = 0; i < 50000; i++){
            int  n = rand.nextInt(6) + 1;
           switch (n) {
               case 1:
                   yksi++;
                   break;
               case 2:
                   kaksi++;
                   break;
               case 3:
                   kolme++;
                   break;
               case 4:
                   nelja++;
                   break;
               case 5:
                   viisi++;
                   break;
               default:
                   kuusi++;
                   break;
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    infoBox("1: "+yksi
            +"\n2: "+kaksi
            +"\n3: "+kolme
            +"\n4: "+nelja
            +"\n5: "+viisi
            +"\n6: "+kuusi, "Onnistui!");
    }
    private int visibility(){
        int modifier = 0;
        if (lI.isSelected()== true){
            modifier = modifier + 1;
        }
        if (lII.isSelected()== true){
            modifier = modifier + 3;
        }
        if (lIII.isSelected()== true){
            modifier = modifier + 6;
        }
        return modifier;
    }
    private int lightning(){
        int modifier = 0;
        if (vI.isSelected()== true){
            modifier = modifier + 1;
        }
        if (vII.isSelected()== true){
            modifier = modifier + 3;
        }
        if (vIII.isSelected()== true){
            modifier = modifier + 6;
        }
        return modifier;
    }
    private int wind(){
        int modifier = 0;
        if (wI.isSelected()== true){
            modifier = modifier + 1;
        }
        if (wII.isSelected()== true){
            modifier = modifier + 3;
        }
        if (wIII.isSelected()== true){
            modifier = modifier + 6;
        }
        return modifier;
    }
    private int range(){
        int modifier = 0;
        if (rI.isSelected()== true){
            modifier = modifier + 1;
        }
        if (rII.isSelected()== true){
            modifier = modifier + 3;
        }
        if (rIII.isSelected()== true){
            modifier = modifier + 6;
        }
        return modifier;
    }
    private int situational(){
        int modifier = 0;
        if (sI.isSelected()== true){
            modifier = modifier + 3;
        }
        if (sII.isSelected()== true){
            modifier = modifier + 2;
        }
        if (sIII.isSelected()== true){
            modifier = modifier + 3;
        }
         if (sIV.isSelected()== true){
            modifier = modifier + 2;
        }
        if (sV.isSelected()== true){
            modifier = modifier + 6;
        }
        if (sVI.isSelected()== true){
            modifier = modifier + 4;
        }
         if (sVII.isSelected()== true){
            modifier = modifier - 1;
        }
        if (sVIII.isSelected()== true){
            modifier = modifier - 1;
        }
        if (sIX.isSelected()== true){
            modifier = modifier - 2;
        }
        if (sX.isSelected()== true){
            modifier = modifier + 2;
        }
        return modifier;
    }
     public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new mainMenu().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu about;
    private javax.swing.JMenuItem aboutMenu;
    public javax.swing.JSpinner accuracyValue;
    private javax.swing.JMenu edit;
    private javax.swing.JRadioButton fI;
    private javax.swing.JRadioButton fII;
    private javax.swing.JRadioButton fIII;
    private javax.swing.JRadioButton fIV;
    private javax.swing.JRadioButton fV;
    private javax.swing.JMenu file;
    private javax.swing.ButtonGroup firingGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton lI;
    private javax.swing.JRadioButton lII;
    private javax.swing.JRadioButton lIII;
    private javax.swing.JRadioButton lIV;
    private javax.swing.ButtonGroup lightGlareGroup;
    private javax.swing.JRadioButton rI;
    private javax.swing.JRadioButton rII;
    private javax.swing.JRadioButton rIII;
    private javax.swing.JRadioButton rIV;
    private javax.swing.ButtonGroup rangeGroup;
    private javax.swing.JCheckBox sI;
    private javax.swing.JCheckBox sII;
    private javax.swing.JCheckBox sIII;
    private javax.swing.JCheckBox sIV;
    private javax.swing.JRadioButton sIX;
    private javax.swing.JCheckBox sV;
    private javax.swing.JCheckBox sVI;
    private javax.swing.JCheckBox sVII;
    private javax.swing.JRadioButton sVIII;
    private javax.swing.JCheckBox sX;
    private javax.swing.JRadioButton sXI;
    private javax.swing.JButton shoot;
    public javax.swing.JSpinner shootingValue;
    private javax.swing.ButtonGroup situanationalGroup;
    private javax.swing.JRadioButton vI;
    private javax.swing.JRadioButton vII;
    private javax.swing.JRadioButton vIII;
    private javax.swing.JRadioButton vIV;
    private javax.swing.ButtonGroup visibilityGroup;
    private javax.swing.JRadioButton wI;
    private javax.swing.JRadioButton wII;
    private javax.swing.JRadioButton wIII;
    private javax.swing.JRadioButton wIV;
    private javax.swing.ButtonGroup windGroup;
    // End of variables declaration//GEN-END:variables
}